import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '../hooks/useAuth';

export type LanguageCode = 'en' | 'hi' | 'kn' | 'ta' | 'te' | 'ml' | 'mr' | 'bn';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  native: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
];

export interface Translations {
  howItWorks: string;
  privacy: string;
  logIn: string;
  getStarted: string;
  goToDashboard: string;
  heroEyebrow: string;
  heroTitleLine1: string;
  heroTitleLine2: string;
  heroSubtitle: string;
  startConversation: string;
  seeHowItWorks: string;
  encryptedAndPrivate: string;
  noDiagnosis: string;
  youControlSharing: string;
  conversationInProgress: string;
  listening: string;
  speakNaturally: string;
  heroCardQuestion: string;
  statementKicker: string;
  statementHeadingLine1: string;
  statementHeadingLine2: string;
  howItWorksEyebrow: string;
  howItWorksTitleLine1: string;
  howItWorksTitleLine2: string;
  step1Title: string;
  step1Desc: string;
  step2Title: string;
  step2Desc: string;
  step3Title: string;
  step3Desc: string;
  multilingualEyebrow: string;
  multilingualTitleLine1: string;
  multilingualTitleLine2: string;
  multilingualDesc: string;
  privacyEyebrow: string;
  privacyTitle: string;
  privacySubtitle: string;
  privacyCard1Title: string;
  privacyCard1Desc: string;
  privacyCard2Title: string;
  privacyCard2Desc: string;
  privacyCard3Title: string;
  privacyCard3Desc: string;
  finalCtaTitleLine1: string;
  finalCtaTitleLine2: string;
  finalCtaSub: string;
  beginConversation: string;
  // Dashboard & App Navigation
  overview?: string;
  conversations?: string;
  reports?: string;
  goodMorning?: string;
  goodAfternoon?: string;
  goodEvening?: string;
  takeAMoment?: string;
  privateSpaceToTalk?: string;
  whatsOnYourMind?: string;
  speakFreely1015?: string;
  nothingSharedWithoutYou?: string;
  recentConversations?: string;
  viewAll?: string;
  noConversationsYet?: string;
  whenYouStartSession?: string;
  reportReady?: string;
  inProgress?: string;
  viewReport?: string;
  nextAppointment?: string;
  noAppointmentAdded?: string;
  addDateToKeepPrep?: string;
  addAppointment?: string;
  crisisNotice?: string;
  // Conversation Session Page
  sessionTimer?: string;
  sessionHeadline?: string;
  speakPlaceholder?: string;
  typePlaceholder?: string;
  sendConversation?: string;
  finishAndSummary?: string;
  synthesizingSummary?: string;
  // Summary Report Page
  reportSummaryTitle?: string;
  privateIntakeDoc?: string;
  reportNotice?: string;
  inYourWords?: string;
  summaryOverview?: string;
  print?: string;
  shareWithTherapist?: string;
  linkCopied?: string;
  returnToDashboard?: string;
  logoName?: string;
  footerSlogan?: string;
  terms?: string;
  contact?: string;
  footerDisclaimer?: string;
}

const TRANSLATIONS: Record<LanguageCode, Translations> = {
  en: {
    howItWorks: 'How it works',
    privacy: 'Privacy',
    logIn: 'Log in',
    getStarted: 'Get started',
    goToDashboard: 'Go to Dashboard',
    heroEyebrow: 'A calmer first step',
    heroTitleLine1: 'Find the words',
    heroTitleLine2: 'before therapy.',
    heroSubtitle: 'A private, voice-first conversation that helps you understand what you’re feeling—and gives your therapist a clearer place to begin.',
    startConversation: 'Start a private conversation',
    seeHowItWorks: 'See how it works',
    encryptedAndPrivate: 'Encrypted & private',
    noDiagnosis: 'No diagnosis',
    youControlSharing: 'You control sharing',
    conversationInProgress: 'Conversation in progress',
    listening: 'Listening',
    speakNaturally: 'Speak naturally. There’s no right answer.',
    heroCardQuestion: '"What has been feeling heaviest lately?"',
    statementKicker: 'Starting therapy can feel overwhelming.',
    statementHeadingLine1: 'Triora helps you arrive',
    statementHeadingLine2: 'already understood.',
    howItWorksEyebrow: 'HOW IT WORKS',
    howItWorksTitleLine1: 'Three gentle steps.',
    howItWorksTitleLine2: 'One clearer beginning.',
    step1Title: 'Speak freely',
    step1Desc: 'Have an open-ended voice conversation in the language that feels most natural.',
    step2Title: 'See the patterns',
    step2Desc: 'Triora organizes what you shared into themes, context, and what matters most to you.',
    step3Title: 'Share on your terms',
    step3Desc: 'Review your summary first. Download it or share it with your therapist when you’re ready.',
    multilingualEyebrow: 'MULTILINGUAL CONVERSATION',
    multilingualTitleLine1: 'Your language.',
    multilingualTitleLine2: 'Your pace. Your story.',
    multilingualDesc: 'Expressing emotions is easier in the words closest to home. Triora supports eight Indian languages, with a patient listener that never rushes or interrupts.',
    privacyEyebrow: 'PRIVACY BY DESIGN',
    privacyTitle: 'Your story stays yours.',
    privacySubtitle: 'Your conversations are encrypted. Nothing is shared without your action, and you can delete your data at any time.',
    privacyCard1Title: 'Encrypted in transit and at rest',
    privacyCard1Desc: 'Industry-standard encryption guarantees that your private conversations remain strictly secure.',
    privacyCard2Title: 'Short-lived speech tokens',
    privacyCard2Desc: 'Audio processing uses temporary tokens that expire immediately after your conversation ends.',
    privacyCard3Title: 'Clear consent before sharing',
    privacyCard3Desc: 'Your summary is only accessible to you until you explicitly choose to export or send it to your therapist.',
    finalCtaTitleLine1: 'Take the first step',
    finalCtaTitleLine2: 'in your own words.',
    finalCtaSub: 'About 10–15 minutes. Private by default.',
    beginConversation: 'Begin your conversation',
    overview: 'Home',
    conversations: 'Conversations',
    reports: 'Reports',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    takeAMoment: 'Take a moment. There’s no rush here.',
    privateSpaceToTalk: 'A PRIVATE SPACE TO TALK',
    whatsOnYourMind: 'What’s been on your mind?',
    speakFreely1015: 'Speak freely for 10–15 minutes. Triora will listen and help organize what you want your therapist to understand.',
    nothingSharedWithoutYou: 'Nothing is shared without you',
    recentConversations: 'Recent conversations',
    viewAll: 'View all',
    noConversationsYet: 'No conversations recorded yet',
    whenYouStartSession: 'When you start a session, your private summaries will appear here.',
    reportReady: 'Report ready',
    inProgress: 'In progress',
    viewReport: 'View report',
    nextAppointment: 'YOUR NEXT APPOINTMENT',
    noAppointmentAdded: 'No appointment added',
    addDateToKeepPrep: 'Add a date to keep your preparation in one place.',
    addAppointment: '+ Add appointment',
    crisisNotice: 'Need immediate support? Triora isn’t a crisis service. If you are in emergency distress, please reach out to local crisis numbers or healthcare professionals immediately.',
    sessionTimer: 'Conversation session',
    sessionHeadline: 'Take your time. Speak whenever you are ready.',
    speakPlaceholder: 'Your spoken words will appear here in real time...',
    typePlaceholder: 'Or type your thoughts here if you prefer not to speak...',
    sendConversation: 'Send response',
    finishAndSummary: 'Finish & generate summary',
    synthesizingSummary: 'Synthesizing your conversation into a structured report...',
    reportSummaryTitle: 'Conversation Summary',
    privateIntakeDoc: 'Private Intake Document',
    reportNotice: 'This summary was generated from your conversation. Review and edit it before sharing with your therapist.',
    inYourWords: 'IN YOUR WORDS',
    summaryOverview: 'Summary Overview',
    print: 'Print',
    shareWithTherapist: 'Share with therapist',
    linkCopied: 'Link copied!',
    returnToDashboard: 'Return to Dashboard',
      logoName: "triora",
    footerSlogan: "Voice-first preparation for a more human beginning to therapy.",
    terms: "Terms",
    contact: "Contact",
    footerDisclaimer: "© 2026 Triora. Triora is not a crisis service or a substitute for medical care.",
  },
  hi: {
    howItWorks: 'यह कैसे काम करता है',
    privacy: 'गोपनीयता',
    logIn: 'लॉग इन करें',
    getStarted: 'शुरू करें',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    heroEyebrow: 'एक शांत पहला कदम',
    heroTitleLine1: 'थेरेपी से पहले',
    heroTitleLine2: 'अपने शब्द खोजें।',
    heroSubtitle: 'एक निजी, आवाज-आधारित बातचीत जो आपको यह समझने में मदद करती है कि आप क्या महसूस कर रहे हैं।',
    startConversation: 'एक निजी बातचीत शुरू करें',
    seeHowItWorks: 'देखें यह कैसे काम करता है',
    encryptedAndPrivate: 'एन्क्रिप्टेड और सुरक्षित',
    noDiagnosis: 'कोई मेडिकल निदान नहीं',
    youControlSharing: 'शेयरिंग आपके नियंत्रण में',
    conversationInProgress: 'बातचीत जारी है',
    listening: 'सुन रहे हैं',
    speakNaturally: 'सहजता से बोलें। कोई सही या गलत जवाब नहीं है।',
    heroCardQuestion: '"आजकल सबसे भारी क्या महसूस हो रहा है?"',
    statementKicker: 'थेरेपी शुरू करना मुश्किल लग सकता है।',
    statementHeadingLine1: 'त्रियोरा आपको पहले से',
    statementHeadingLine2: 'समझा हुआ महसूस कराता है।',
    howItWorksEyebrow: 'यह कैसे काम करता है',
    howItWorksTitleLine1: 'तीन सरल कदम।',
    howItWorksTitleLine2: 'एक स्पष्ट शुरुआत।',
    step1Title: 'खुुलकर बोलें',
    step1Desc: 'अपनी पसंदीदा भाषा में खुलकर बातचीत करें।',
    step2Title: 'पैटर्न समझें',
    step2Desc: 'त्रियोरा आपकी बातों को मुख्य विषयों और महत्वपूर्ण बिंदुओं में व्यवस्थित करता है।',
    step3Title: 'अपनी शर्तों पर साझा करें',
    step3Desc: 'पहले अपना सारांश देखें। जब आप तैयार हों तभी अपने थेरेपिस्ट के साथ साझा करें।',
    multilingualEyebrow: 'बहुभाषी बातचीत',
    multilingualTitleLine1: 'आपकी भाषा।',
    multilingualTitleLine2: 'आपकी गति। आपकी कहानी।',
    multilingualDesc: 'अपनी मातृभाषा में भावनाओं को व्यक्त करना आसान होता है। त्रियोरा 8 भारतीय भाषाओं का समर्थन करता है।',
    privacyEyebrow: 'गोपनीयता डिज़ाइन',
    privacyTitle: 'आपकी कहानी सिर्फ आपकी है।',
    privacySubtitle: 'आपकी बातचीत पूरी तरह एन्क्रिप्टेड है और आपकी अनुमति के बिना साझा नहीं की जाती।',
    privacyCard1Title: 'पूर्ण एन्क्रिप्शन',
    privacyCard1Desc: 'उद्योग-मानक एन्क्रिप्शन आपकी बातचीत की सुरक्षा सुनिश्चित करता है।',
    privacyCard2Title: 'अस्थायी टोकन',
    privacyCard2Desc: 'बातचीत समाप्त होते ही ऑडियो टोकन तुरंत समाप्त हो जाते हैं।',
    privacyCard3Title: 'स्पष्ट सहमति',
    privacyCard3Desc: 'जब तक आप स्वयं निर्यात नहीं करते, आपका सारांश केवल आपके पास रहता है।',
    finalCtaTitleLine1: 'पहला कदम उठाएं',
    finalCtaTitleLine2: 'अपने खुद के शब्दों में।',
    finalCtaSub: 'लगभग 10-15 मिनट। डिफ़ॉल्ट रूप से निजी।',
    beginConversation: 'अपनी बातचीत शुरू करें',
      overview: 'अवलोकन',
    conversations: 'बातचीत',
    reports: 'रिपोर्ट',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    takeAMoment: 'थोड़ा समय लें। यहाँ कोई जल्दी नहीं है।',
    privateSpaceToTalk: 'बात करने के लिए एक निजी जगह',
    whatsOnYourMind: 'आपके मन में क्या है?',
    speakFreely1015: '10-15 मिनट तक खुलकर बोलें। ट्रियोरा सुनेगा और जो आप अपने थेरेपिस्ट को समझाना चाहते हैं उसे व्यवस्थित करने में मदद करेगा।',
    nothingSharedWithoutYou: 'आपकी अनुमति के बिना कुछ भी साझा नहीं किया जाएगा',
    recentConversations: 'हाल की बातचीत',
    viewAll: 'सभी देखें',
    noConversationsYet: 'अभी तक कोई बातचीत रिकॉर्ड नहीं की गई है',
    whenYouStartSession: 'जब आप कोई सत्र शुरू करते हैं, तो आपके निजी सारांश यहाँ दिखाई देंगे।',
    reportReady: 'रिपोर्ट तैयार',
    inProgress: 'प्रगति पर',
    viewReport: 'रिपोर्ट देखें',
    nextAppointment: 'आपकी अगली अपॉइंटमेंट',
    noAppointmentAdded: 'कोई अपॉइंटमेंट नहीं जोड़ी गई',
    addDateToKeepPrep: 'अपनी तैयारी को एक जगह रखने के लिए एक तारीख जोड़ें।',
    addAppointment: '+ अपॉइंटमेंट जोड़ें',
    crisisNotice: 'तत्काल सहायता चाहिए? ट्रियोरा क्राइसिस सर्विस नहीं है। यदि आप आपातकालीन संकट में हैं, तो कृपया तुरंत स्थानीय क्राइसिस नंबर या स्वास्थ्य पेशेवरों से संपर्क करें।',
    sessionTimer: 'बातचीत सत्र',
    sessionHeadline: 'अपना समय लें। जब आप तैयार हों तब बोलें।',
    speakPlaceholder: 'आपके बोले गए शब्द यहाँ वास्तविक समय में दिखाई देंगे...',
    typePlaceholder: 'या यदि आप बोलना नहीं चाहते तो अपने विचार यहाँ टाइप करें...',
    sendConversation: 'प्रतिक्रिया भेजें',
    finishAndSummary: 'समाप्त करें और सारांश बनाएँ',
    synthesizingSummary: 'आपकी बातचीत को एक संरचित रिपोर्ट में संश्लेषित किया जा रहा है...',
    reportSummaryTitle: 'बातचीत का सारांश',
    privateIntakeDoc: 'निजी इंटेक दस्तावेज़',
    reportNotice: 'यह सारांश आपकी बातचीत से तैयार किया गया है। अपने थेरेपिस्ट के साथ साझा करने से पहले इसकी समीक्षा और संपादन करें।',
    inYourWords: 'आपके शब्दों में',
    summaryOverview: 'सारांश अवलोकन',
    print: 'प्रिंट करें',
    shareWithTherapist: 'थेरेपिस्ट के साथ साझा करें',
    linkCopied: 'लिंक कॉपी किया गया!',
    returnToDashboard: 'डैशबोर्ड पर लौटें',
      logoName: "त्रियोरा",
    footerSlogan: "थेरेपी की अधिक मानवीय शुरुआत के लिए आवाज-आधारित तैयारी।",
    terms: "शर्तें",
    contact: "संपर्क",
    footerDisclaimer: "© 2026 त्रियोरा। त्रियोरा कोई क्राइसिस सेवा या चिकित्सा देखभाल का विकल्प नहीं है।",
  },
  kn: {
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    privacy: 'ಗೌಪ್ಯತೆ',
    logIn: 'ಲಾಗಿನ್ ಮಾಡಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    goToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    heroEyebrow: 'ಒಂದು ಪ್ರಶಾಂತ ಮೊದಲ ಹೆಜ್ಜೆ',
    heroTitleLine1: 'ಥೆರಪಿಗೂ ಮುನ್ನ',
    heroTitleLine2: 'ನಿಮ್ಮ ಪದಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
    heroSubtitle: 'ನೀವು ಏನನ್ನು ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುವ ಖಾಸಗಿ ಧ್ವನಿ ಸಂಭಾಷಣೆ.',
    startConversation: 'ಖಾಸಗಿ ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    seeHowItWorks: 'ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ನೋಡಿ',
    encryptedAndPrivate: 'ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ & ಖಾಸಗಿ',
    noDiagnosis: 'ಯಾವುದೇ ರೋಗನಿರ್ಣಯವಿಲ್ಲ',
    youControlSharing: 'ಹಂಚಿಕೆ ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿದೆ',
    conversationInProgress: 'ಸಂಭಾಷಣೆ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    listening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ',
    speakNaturally: 'ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.',
    heroCardQuestion: '"ಇತ್ತೀಚೆಗೆ ನಿಮಗೆ ಯಾವುದು ಕಷ್ಟವೆನಿಸುತ್ತಿದೆ?"',
    statementKicker: 'ಥೆರಪಿ ಪ್ರಾರಂಭಿಸುವುದು ಸವಾಲೆನಿಸಬಹುದು.',
    statementHeadingLine1: 'ಟ್ರಿಯೋರಾ ನಿಮಗೆ ಮುಂಚಿತವಾಗಿಯೇ',
    statementHeadingLine2: 'ಅರ್ಥ ಮಾಡಿಕೊಳ್ಳಲು ನೆರವಾಗುತ್ತದೆ.',
    howItWorksEyebrow: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    howItWorksTitleLine1: 'ಮೂರು ಸರಳ ಹಂತಗಳು.',
    howItWorksTitleLine2: 'ಒಂದು ಸ್ಪಷ್ಟ ಆರಂಭ.',
    step1Title: 'ಮುಕ್ತವಾಗಿ ಮಾತನಾಡಿ',
    step1Desc: 'ನಿಮಗೆ ಅತ್ಯಂತ ಸಹಜವೆನಿಸುವ ಭಾಷೆಯಲ್ಲಿ ಮುಕ್ತವಾಗಿ ಧ್ವನಿ ಸಂಭಾಷಣೆ ನಡೆಸಿ.',
    step2Title: 'ವಿನ್ಯಾಸಗಳನ್ನು ಗಮನಿಸಿ',
    step2Desc: 'ಟ್ರಿಯೋರಾ ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಸಂಘಟಿಸುತ್ತದೆ.',
    step3Title: 'ನಿಮ್ಮಿಷ್ಟದಂತೆ ಹಂಚಿಕೊಳ್ಳಿ',
    step3Desc: 'ಮೊದಲು ನಿಮ್ಮ ಸಾರಾಂಶವನ್ನು ಪರಿಶೀಲಿಸಿ.',
    multilingualEyebrow: 'ಬಹುಭಾಷಾ ಸಂಭಾಷಣೆ',
    multilingualTitleLine1: 'ನಿಮ್ಮ ಭಾಷೆ.',
    multilingualTitleLine2: 'ನಿಮ್ಮ ವೇಗ. ನಿಮ್ಮ ಕಥೆ.',
    multilingualDesc: 'ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಭಾವನೆಗಳನ್ನು ವ್ಯಕ್ತಪಡಿಸುವುದು ಸುಲಭ. ಟ್ರಿಯೋರಾ 8 ಭಾರತೀಯ ಭಾಷೆಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ.',
    privacyEyebrow: 'ಗೌಪ್ಯತೆ ವಿನ್ಯಾಸ',
    privacyTitle: 'ನಿಮ್ಮ ಕಥೆ ನಿಮಗೇ ಸೇರಿದ್ದು.',
    privacySubtitle: 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತವೆ.',
    privacyCard1Title: 'ಪೂರ್ಣ ಎನ್‌ಕ್ರಿಪ್ಶನ್',
    privacyCard1Desc: 'ನಿಮ್ಮ ಖಾಸಗಿ ಸಂಭಾಷಣೆಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿರಿಸುತ್ತದೆ.',
    privacyCard2Title: 'ತಾತ್ಕಾಲಿಕ ಟೋಕನ್‌ಗಳು',
    privacyCard2Desc: 'ಸಂಭಾಷಣೆ ಮುಗಿದ ತಕ್ಷಣ ಆಡಿಯೋ ಟೋಕನ್‌ಗಳು ಕೊನೆಗೊಳ್ಳುತ್ತವೆ.',
    privacyCard3Title: 'ಸ್ಪಷ್ಟ ಒಪ್ಪಿಗೆ',
    privacyCard3Desc: 'ನೀವು ಹಂಚಿಕೊಳ್ಳಲು ನಿರ್ಧರಿಸುವವರೆಗೂ ನಿಮ್ಮ ಸಾರಾಂಶ ನಿಮಗಷ್ಟೇ ಲಭ್ಯ.',
    finalCtaTitleLine1: 'ಮೊದಲ ಹೆಜ್ಜೆ ಇಡಿ',
    finalCtaTitleLine2: 'ನಿಮ್ಮದೇ ಮಾತುಗಳಲ್ಲಿ.',
    finalCtaSub: 'ಸುಮಾರು 10-15 ನಿಮಿಷಗಳು.',
    beginConversation: 'ನಿಮ್ಮ ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
      overview: 'ಅವಲೋಕನ',
    conversations: 'ಸಂಭಾಷಣೆಗಳು',
    reports: 'ವರದಿಗಳು',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    takeAMoment: 'ಸ್ವಲ್ಪ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಿ. ಇಲ್ಲಿ ಆತುರವಿಲ್ಲ.',
    privateSpaceToTalk: 'ಮಾತನಾಡಲು ಖಾಸಗಿ ಸ್ಥಳ',
    whatsOnYourMind: 'ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ?',
    speakFreely1015: '10-15 ನಿಮಿಷ ಮುಕ್ತವಾಗಿ ಮಾತನಾಡಿ.',
    nothingSharedWithoutYou: 'ನಿಮ್ಮ ಅನುಮತಿಯಿಲ್ಲದೆ ಏನನ್ನೂ ಹಂಚಿಕೊಳ್ಳಲಾಗುವುದಿಲ್ಲ',
    recentConversations: 'ಇತ್ತೀಚಿನ ಸಂಭಾಷಣೆಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    noConversationsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ',
    whenYouStartSession: 'ನೀವು ಸೆಷನ್ ಪ್ರಾರಂಭಿಸಿದಾಗ ಸಾರಾಂಶಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
    reportReady: 'ವರದಿ ಸಿದ್ಧವಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    viewReport: 'ವರದಿ ವೀಕ್ಷಿಸಿ',
    nextAppointment: 'ನಿಮ್ಮ ಮುಂದಿನ ಅಪಾಯಿಂಟ್ಮೆಂಟ್',
    noAppointmentAdded: 'ಯಾವುದೇ ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಸೇರಿಸಿಲ್ಲ',
    addDateToKeepPrep: 'ದಿನಾಂಕವನ್ನು ಸೇರಿಸಿ.',
    addAppointment: '+ ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಸೇರಿಸಿ',
    crisisNotice: 'ತಕ್ಷಣದ ಬೆಂಬಲ ಬೇಕೇ? ಟ್ರಿಯೋರಾ ಬಿಕ್ಕಟ್ಟು ಸೇವೆಯಲ್ಲ. ದಯವಿಟ್ಟು ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    sessionTimer: 'ಸಂಭಾಷಣೆ ಸೆಷನ್',
    sessionHeadline: 'ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಿ. ಸಿದ್ಧವಾದಾಗ ಮಾತನಾಡಿ.',
    speakPlaceholder: 'ನಿಮ್ಮ ಮಾತುಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ...',
    typePlaceholder: 'ಅಥವಾ ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    sendConversation: 'ಕಳುಹಿಸಿ',
    finishAndSummary: 'ಮುಕ್ತಾಯಗೊಳಿಸಿ & ಸಾರಾಂಶ ರಚಿಸಿ',
    synthesizingSummary: 'ಸಾರಾಂಶವನ್ನು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ...',
    reportSummaryTitle: 'ಸಂಭಾಷಣೆ ಸಾರಾಂಶ',
    privateIntakeDoc: 'ಖಾಸಗಿ ದಾಖಲೆ',
    reportNotice: 'ಥೆರಪಿಸ್ಟ್ ಜೊತೆ ಹಂಚಿಕೊಳ್ಳುವ ಮುನ್ನ ಪರಿಶೀಲಿಸಿ.',
    inYourWords: 'ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ',
    summaryOverview: 'ಸಾರಾಂಶ ಅವಲೋಕನ',
    print: 'ಮುದ್ರಿಸಿ',
    shareWithTherapist: 'ಥೆರಪಿಸ್ಟ್ ಜೊತೆ ಹಂಚಿಕೊಳ್ಳಿ',
    linkCopied: 'ಲಿಂಕ್ ಕಾಪಿ ಮಾಡಲಾಗಿದೆ!',
    returnToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
      logoName: "ಟ್ರಿಯೋರಾ",
    footerSlogan: "ಥೆರಪಿಯ ಮಾನವೀಯ ಆರಂಭಕ್ಕಾಗಿ ಧ್ವನಿ-ಮೊದಲ ತಯಾರಿ.",
    terms: "ನಿಯಮಗಳು",
    contact: "ಸಂಪರ್ಕಿಸಿ",
    footerDisclaimer: "© 2026 ಟ್ರಿಯೋರಾ. ಟ್ರಿಯೋರಾ ಬಿಕ್ಕಟ್ಟು ಸೇವೆಯಲ್ಲ ಅಥವಾ ವೈದ್ಯಕೀಯ ಆರೈಕೆಗೆ ಪರ್ಯಾಯವಲ್ಲ.",
  },
  ta: {
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    privacy: 'தனியுரிமை',
    logIn: 'உள்நுழைக',
    getStarted: 'தொடங்கவும்',
    goToDashboard: 'டேஷ்போர்டிற்குச் செல்லவும்',
    heroEyebrow: 'ஒரு அமைதியான முதல் படி',
    heroTitleLine1: 'சிகிச்சைக்கு முன்',
    heroTitleLine2: 'உங்கள் வார்த்தைகளைக் கண்டறியவும்.',
    heroSubtitle: 'நீங்கள் என்ன உணர்கிறீர்கள் என்பதைப் புரிந்துகொள்ள உதவும் ஒரு தனிப்பட்ட குரல் உரையாடல்.',
    startConversation: 'தனிப்பட்ட உரையாடலைத் தொடங்கவும்',
    seeHowItWorks: 'எவ்வாறு செயல்படுகிறது எனப் பார்க்கவும்',
    encryptedAndPrivate: 'பாதுகாக்கப்பட்ட & தனிப்பட்ட',
    noDiagnosis: 'மருத்துவக் கணிப்பு இல்லை',
    youControlSharing: 'பகிர்வு உங்கள் கட்டுப்பாட்டில்',
    conversationInProgress: 'உரையாடல் நடப்பில் உள்ளது',
    listening: 'கேட்கிறது',
    speakNaturally: 'இயல்பாகப் பேசுங்கள்.',
    heroCardQuestion: '"சமீபத்தில் உங்களுக்கு எது கடினமாக இருந்தது?"',
    statementKicker: 'சிகிச்சையைத் தொடங்குவது கடினமாக இருக்கலாம்.',
    statementHeadingLine1: 'டிரியோரா உங்களுக்கு',
    statementHeadingLine2: 'தெளிவான தொடக்கத்தை அளிக்கிறது.',
    howItWorksEyebrow: 'செயல்முறை',
    howItWorksTitleLine1: 'மூன்று எளிய படிகள்.',
    howItWorksTitleLine2: 'ஒரு தெளிவான தொடக்கம்.',
    step1Title: 'சுதந்திரமாகப் பேசுங்கள்',
    step1Desc: 'உங்கள் தாய்மொழியில் இயல்பாக உரையாடுங்கள்.',
    step2Title: 'முறைகளைப் புரிந்து கொள்ளுங்கள்',
    step2Desc: 'டிரியோரா உங்கள் எண்ணங்களை முறைப்படுத்துகிறது.',
    step3Title: 'உங்கள் விருப்பப்படி பகிருங்கள்',
    step3Desc: 'முதலில் உங்கள் சுருக்கத்தைப் பாருங்கள்.',
    multilingualEyebrow: 'பலமொழி உரையாடல்',
    multilingualTitleLine1: 'உங்கள் மொழி.',
    multilingualTitleLine2: 'உங்கள் வேகம். உங்கள் கதை.',
    multilingualDesc: 'உங்கள் சொந்த மொழியில் உணர்வுகளை வெளிப்படுத்துவது எளிது.',
    privacyEyebrow: 'தனியுரிமை பாதுகாப்பு',
    privacyTitle: 'உங்கள் கதை உங்களுடையது மட்டுமே.',
    privacySubtitle: 'உங்கள் உரையாடல்கள் முற்றிலும் பாதுகாக்கப்பட்டவை.',
    privacyCard1Title: 'முழுமையான பாதுகாப்பு',
    privacyCard1Desc: 'தொழில்துறை தரத்திலான பாதுகாப்பு.',
    privacyCard2Title: 'தற்காலிக அணுகல்',
    privacyCard2Desc: 'உரையாடல் முடிந்ததும் ஆடியோ தரவு நீக்கப்படும்.',
    privacyCard3Title: 'தெளிவான ஒப்புதல்',
    privacyCard3Desc: 'நீங்கள் பகிரும் வரை தகவல்கள் ரகசியமாக இருக்கும்.',
    finalCtaTitleLine1: 'முதல் அடியை எடுத்து வையுங்கள்',
    finalCtaTitleLine2: 'உங்கள் சொந்த வார்த்தைகளில்.',
    finalCtaSub: 'சுமார் 10-15 நிமிடங்கள்.',
    beginConversation: 'உங்கள் உரையாடலைத் தொடங்குங்கள்',
      overview: 'கண்ணோட்டம்',
    conversations: 'உரையாடல்கள்',
    reports: 'அறிக்கைகள்',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    takeAMoment: 'சிறிது நேரம் எடுத்துக்கொள்ளுங்கள். அவசரம் இல்லை.',
    privateSpaceToTalk: 'பேசுவதற்கு ஒரு தனிப்பட்ட இடம்',
    whatsOnYourMind: 'உங்கள் மனதில் என்ன இருக்கிறது?',
    speakFreely1015: '10-15 நிமிடங்கள் சுதந்திரமாக பேசுங்கள்.',
    nothingSharedWithoutYou: 'உங்கள் அனுமதியின்றி எதுவும் பகிரப்படாது',
    recentConversations: 'சமீபத்திய உரையாடல்கள்',
    viewAll: 'அனைத்தையும் காண்க',
    noConversationsYet: 'இன்னும் உரையாடல்கள் இல்லை',
    whenYouStartSession: 'நீங்கள் அமர்வைத் தொடங்கும்போது சுருக்கங்கள் இங்கே தோன்றும்.',
    reportReady: 'அறிக்கை தயார்',
    inProgress: 'செயல்பாட்டில் உள்ளது',
    viewReport: 'அறிக்கையைக் காண்க',
    nextAppointment: 'உங்கள் அடுத்த சந்திப்பு',
    noAppointmentAdded: 'சந்திப்பு எதுவும் சேர்க்கப்படவில்லை',
    addDateToKeepPrep: 'தேதியைச் சேர்க்கவும்.',
    addAppointment: '+ சந்திப்பைச் சேர்',
    crisisNotice: 'உடனடி ஆதரவு தேவையா? தயவுசெய்து மருத்துவர்களைத் தொடர்பு கொள்ளவும்.',
    sessionTimer: 'உரையாடல் அமர்வு',
    sessionHeadline: 'நேரம் எடுத்துக் கொள்ளுங்கள். தயாரானதும் பேசுங்கள்.',
    speakPlaceholder: 'உங்கள் வார்த்தைகள் இங்கே தோன்றும்...',
    typePlaceholder: 'அல்லது உங்கள் எண்ணங்களை இங்கே தட்டச்சு செய்க...',
    sendConversation: 'அனுப்பு',
    finishAndSummary: 'முடித்து சுருக்கத்தை உருவாக்கு',
    synthesizingSummary: 'சுருக்கத்தை தயார் செய்கிறது...',
    reportSummaryTitle: 'உரையாடல் சுருக்கம்',
    privateIntakeDoc: 'தனிப்பட்ட ஆவணம்',
    reportNotice: 'பகிர்வதற்கு முன் மதிப்பாய்வு செய்யவும்.',
    inYourWords: 'உங்கள் வார்த்தைகளில்',
    summaryOverview: 'சுருக்கமான கண்ணோட்டம்',
    print: 'அச்சிடு',
    shareWithTherapist: 'பகிர்',
    linkCopied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    returnToDashboard: 'முகப்புப்பக்கத்திற்குத் திரும்பு',
      logoName: "ட்ரியோரா",
    footerSlogan: "சிகிச்சையின் மனிதாபிமான தொடக்கத்திற்கான குரல்-முதல் தயாரிப்பு.",
    terms: "விதிமுறைகள்",
    contact: "தொடர்பு",
    footerDisclaimer: "© 2026 ட்ரியோரா. ட்ரியோரா நெருக்கடி சேவை அல்லது மருத்துவ பராமரிப்புக்கு மாற்றாக இல்லை.",
  },
  te: {
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    privacy: 'గోప్యత',
    logIn: 'లాగిన్ చేయండి',
    getStarted: 'ప్రారంభించండి',
    goToDashboard: 'డాష్‌బోర్డ్‌కి వెళ్లండి',
    heroEyebrow: 'ఒక ప్రశాంతమైన మొదటి అడుగు',
    heroTitleLine1: 'థెరపీకి ముందే',
    heroTitleLine2: 'మీ మాటలను కనుగొనండి.',
    heroSubtitle: 'మీరు ఏమనుకుంటున్నారో అర్థం చేసుకోవడానికి సహాయపడే వ్యక్తిగత వాయిస్ సంభాషణ.',
    startConversation: 'వ్యక్తిగత సంభాషణను ప్రారంభించండి',
    seeHowItWorks: 'ఇది ఎలా పనిచేస్తుందో చూడండి',
    encryptedAndPrivate: 'ఎన్‌క్రిప్ట్ చేయబడిన & సురక్షితమైన',
    noDiagnosis: 'మెడికల్ నిర్ధారణ లేదు',
    youControlSharing: 'షేరింగ్ మీ నియంత్రణలో ఉంటుంది',
    conversationInProgress: 'సంభాషణ జరుగుతోంది',
    listening: 'వింటోంది',
    speakNaturally: 'సహజంగా మాట్లాడండి.',
    heroCardQuestion: '"ఇటీవల మీకు అత్యంత భారంగా అనిపించినది ఏమిటి?"',
    statementKicker: 'థెరపీ ప్రారంభించడం కష్టంగా అనిపించవచ్చు.',
    statementHeadingLine1: 'ట్రియోరా మీకు ముందే',
    statementHeadingLine2: 'అర్థమయ్యేలా చేస్తుంది.',
    howItWorksEyebrow: 'ఇది ఎలా పనిచేస్తుంది',
    howItWorksTitleLine1: 'మూడు సులభమైన దశలు.',
    howItWorksTitleLine2: 'ఒక స్పష్టమైన ప్రారంభం.',
    step1Title: 'స్వేచ్ఛగా మాట్లాడండి',
    step1Desc: 'మీకు అనుకూలమైన భాషలో సంభాషణ జరపండి.',
    step2Title: 'వివరాలను గమనించండి',
    step2Desc: 'ట్రియోరా మీ ఆలోచనలను క్రమబద్ధీకరిస్తుంది.',
    step3Title: 'మీ ఇష్టప్రకారం షేర్ చేయండి',
    step3Desc: 'ముందుగా మీ సారాంశాన్ని చూడండి.',
    multilingualEyebrow: 'బహుభాషా సంభాషణ',
    multilingualTitleLine1: 'మీ భాష.',
    multilingualTitleLine2: 'మీ వేగం. మీ కథ.',
    multilingualDesc: 'మీ సొంత భాషలో భావాలను వ్యక్తపరచడం సులభం.',
    privacyEyebrow: 'గోప్యతా డిజైన్',
    privacyTitle: 'మీ కథ మీదే.',
    privacySubtitle: 'మీ సంభాషణలు పూర్తిగా సురక్షితం.',
    privacyCard1Title: 'సంపూర్ణ భద్రత',
    privacyCard1Desc: 'మీ సంభాషణల భద్రతకు హామీ.',
    privacyCard2Title: 'తాత్కాలిక టోకెన్లు',
    privacyCard2Desc: 'సంభాషణ ముగియగానే డేటా తొలగించబడుతుంది.',
    privacyCard3Title: 'స్పష్టమైన సమ్మతి',
    privacyCard3Desc: 'మీరు షేర్ చేసే వరకు సారాంశం మీ వద్దే ఉంటుంది.',
    finalCtaTitleLine1: 'మొదటి అడుగు వేయండి',
    finalCtaTitleLine2: 'మీ సొంత మాటలలో.',
    finalCtaSub: 'సుమారు 10-15 నిమిషాలు.',
    beginConversation: 'మీ సంభాషణను ప్రారంభించండి',
      overview: 'అవలోకనం',
    conversations: 'సంభాషణలు',
    reports: 'నివేదికలు',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    takeAMoment: 'కాస్త సమయం తీసుకోండి. ఇక్కడ తొందర లేదు.',
    privateSpaceToTalk: 'మాట్లాడటానికి ఒక ప్రైవేట్ స్థలం',
    whatsOnYourMind: 'మీ మనసులో ఏముంది?',
    speakFreely1015: '10–15 నిమిషాలు స్వేచ్ఛగా మాట్లాడండి. ట్రియోరా వింటుంది.',
    nothingSharedWithoutYou: 'మీ అనుమతి లేకుండా ఏమీ షేర్ చేయబడదు',
    recentConversations: 'ఇటీవలి సంభాషణలు',
    viewAll: 'అన్నీ చూడండి',
    noConversationsYet: 'సంభాషణలు ఏవీ రికార్డ్ కాలేదు',
    whenYouStartSession: 'మీరు సెషన్‌ను ప్రారంభించినప్పుడు, మీ సారాంశాలు ఇక్కడ కనిపిస్తాయి.',
    reportReady: 'రిపోర్ట్ సిద్ధంగా ఉంది',
    inProgress: 'ప్రగతిలో ఉంది',
    viewReport: 'రిపోర్ట్ చూడండి',
    nextAppointment: 'మీ తదుపరి అపాయింట్‌మెంట్',
    noAppointmentAdded: 'అపాయింట్‌మెంట్ జోడించబడలేదు',
    addDateToKeepPrep: 'తేదీని జోడించండి.',
    addAppointment: '+ అపాయింట్‌మెంట్ జోడించండి',
    crisisNotice: 'తక్షణ మద్దతు కావాలా? ట్రియోరా ఒక క్రైసిస్ సర్వీస్ కాదు. దయచేసి స్థానిక వైద్యులను సంప్రదించండి.',
    sessionTimer: 'సంభాషణ సెషన్',
    sessionHeadline: 'సమయం తీసుకోండి. సిద్ధంగా ఉన్నప్పుడు మాట్లాడండి.',
    speakPlaceholder: 'మీ పదాలు ఇక్కడ కనిపిస్తాయి...',
    typePlaceholder: 'లేదా మీ ఆలోచనలను ఇక్కడ టైప్ చేయండి...',
    sendConversation: 'పంపండి',
    finishAndSummary: 'ముగించండి & సారాంశం రూపొందించండి',
    synthesizingSummary: 'సారాంశాన్ని సిద్ధం చేస్తోంది...',
    reportSummaryTitle: 'సంభాషణ సారాంశం',
    privateIntakeDoc: 'ప్రైవేట్ డాక్యుమెంట్',
    reportNotice: 'దీన్ని మీ థెరపిస్ట్‌తో పంచుకునే ముందు సమీక్షించండి.',
    inYourWords: 'మీ మాటల్లో',
    summaryOverview: 'సారాంశం అవలోకనం',
    print: 'ప్రింట్ చేయండి',
    shareWithTherapist: 'థెరపిస్ట్‌తో షేర్ చేయండి',
    linkCopied: 'లింక్ కాపీ చేయబడింది!',
    returnToDashboard: 'డ్యాష్‌బోర్డ్‌కు వెళ్లండి',
      logoName: "ట్రియోరా",
    footerSlogan: "థెరపీ ప్రారంభానికి మరింత మానవీయమైన వాయిస్-ఫస్ట్ తయారీ.",
    terms: "నిబంధనలు",
    contact: "సంప్రదించండి",
    footerDisclaimer: "© 2026 ట్రియోరా. ట్రియోరా అనేది క్రైసిస్ సర్వీస్ లేదా వైద్య సంరక్షణకు ప్రత్యామ్నాయం కాదు.",
  },
  ml: {
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    privacy: 'സ്വകാര്യത',
    logIn: 'ലോഗിൻ ചെയ്യുക',
    getStarted: 'ആരംഭിക്കുക',
    goToDashboard: 'ഡാഷ്‌ബോർഡിലേക്ക് പോകുക',
    heroEyebrow: 'ആദ്യത്തെ ശാന്തമായ ചുവടുവെപ്പ്',
    heroTitleLine1: 'തെറാപ്പിക്ക് മുമ്പ്',
    heroTitleLine2: 'നിങ്ങളുടെ വാക്കുകൾ കണ്ടെത്തൂ.',
    heroSubtitle: 'നിങ്ങളുടെ വികാരങ്ങൾ മനസ്സിലാക്കാൻ സഹായിക്കുന്ന ഒരു വ്യക്തിഗത ശബ്ദ സംഭാഷണം.',
    startConversation: 'ഒരു വ്യക്തിഗത സംഭാഷണം ആരംഭിക്കുക',
    seeHowItWorks: 'പ്രവർത്തനം കാണുക',
    encryptedAndPrivate: 'എൻക്രിപ്റ്റ് ചെയ്തതും സ്വകാര്യവും',
    noDiagnosis: 'രോഗനിർണ്ണയമില്ല',
    youControlSharing: 'പങ്കിടൽ നിങ്ങളുടെ നിയന്ത്രണത്തിൽ',
    conversationInProgress: 'സംഭാഷണം നടക്കുന്നു',
    listening: 'ശ്രദ്ധിക്കുന്നു',
    speakNaturally: 'സ്വാഭാവികമായി സംസാരിക്കുക.',
    heroCardQuestion: '"ഈ അടുത്തായി ഏറ്റവും പ്രയാസകരമായി തോന്നിയത് എന്താണ്?"',
    statementKicker: 'തെറാപ്പി ആരംഭിക്കുന്നത് പ്രയാസകരമായി തോന്നാം.',
    statementHeadingLine1: 'ട്രിയോറ നിങ്ങളെ നേരത്തെ തന്നെ',
    statementHeadingLine2: 'മനസ്സിലാക്കാൻ സഹായിക്കുന്നു.',
    howItWorksEyebrow: 'പ്രവർത്തനരീതി',
    howItWorksTitleLine1: 'മൂന്ന് എളുപ്പവഴികൾ.',
    howItWorksTitleLine2: 'ഒരു വ്യക്തമായ തുടക്കം.',
    step1Title: 'തുറന്ന് സംസാരിക്കൂ',
    step1Desc: 'നിങ്ങൾക്ക് ഏറ്റവും അനുയോജ്യമായ ഭാഷയിൽ സംസാരിക്കുക.',
    step2Title: 'കാര്യങ്ങൾ മനസ്സിലാക്കൂ',
    step2Desc: 'ട്രിയോറ നിങ്ങളുടെ ആശയങ്ങൾ ക്രമീകരിക്കുന്നു.',
    step3Title: 'നിങ്ങളുടെ ഇഷ്ടപ്രകാരം പങ്കുവെക്കൂ',
    step3Desc: 'ആദ്യം നിങ്ങളുടെ സംഗ്രഹം പരിശോധിക്കുക.',
    multilingualEyebrow: 'ബഹുഭാഷാ സംഭാഷണം',
    multilingualTitleLine1: 'നിങ്ങളുടെ ഭാഷ.',
    multilingualTitleLine2: 'നിങ്ങളുടെ വേഗം. നിങ്ങളുടെ കഥ.',
    multilingualDesc: 'മാതൃഭാഷയിൽ വികാരങ്ങൾ പ്രകടിപ്പിക്കുന്നത് എളുപ്പമാണ്.',
    privacyEyebrow: 'സ്വകാര്യതാ സുരക്ഷ',
    privacyTitle: 'നിങ്ങളുടെ കഥ നിങ്ങൾക്ക് മാത്രം സ്വന്തം.',
    privacySubtitle: 'നിങ്ങളുടെ സംഭാഷണങ്ങൾ പൂർണ്ണമായും സുരക്ഷിതമാണ്.',
    privacyCard1Title: 'പൂർണ്ണ എൻക്രിപ്ഷൻ',
    privacyCard1Desc: 'നിങ്ങളുടെ വിവരങ്ങൾ സുരക്ഷിതമായിരിക്കും.',
    privacyCard2Title: 'താൽക്കാലിക ടോക്കണുകൾ',
    privacyCard2Desc: 'സംഭാഷണം കഴിയുമ്പോൾ ഓഡിയോ ടോക്കണുകൾ അവസാനിക്കും.',
    privacyCard3Title: 'വ്യക്തമായ സമ്മതം',
    privacyCard3Desc: 'നിങ്ങൾ പങ്കിടുമെന്ന് തീരുമാനിക്കുന്നത് വരെ വിവരങ്ങൾ രഹസ്യമായിരിക്കും.',
    finalCtaTitleLine1: 'ആദ്യ ചുവടുവെപ്പ് നടത്തൂ',
    finalCtaTitleLine2: 'നിങ്ങളുടെ സ്വന്തം വാക്കുകളിൽ.',
    finalCtaSub: 'ഏകദേശം 10-15 മിനിറ്റ്.',
    beginConversation: 'നിങ്ങളുടെ സംഭാഷണം ആരംഭിക്കുക',
      overview: 'അവലോകനം',
    conversations: 'സംഭാഷണങ്ങൾ',
    reports: 'റിപ്പോർട്ടുകൾ',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ചതിരിഞ്ഞ്',
    goodEvening: 'ശുഭ സായാഹ്നം',
    takeAMoment: 'കുറച്ചു സമയം എടുക്കുക. ധൃതിയില്ല.',
    privateSpaceToTalk: 'സംസാരിക്കാൻ ഒരു സ്വകാര്യ ഇടം',
    whatsOnYourMind: 'നിങ്ങളുടെ മനസ്സിലെന്താണ്?',
    speakFreely1015: '10-15 മിനിറ്റ് സ്വതന്ത്രമായി സംസാരിക്കുക.',
    nothingSharedWithoutYou: 'നിങ്ങളുടെ അനുമതിയില്ലാതെ ഒന്നും പങ്കിടില്ല',
    recentConversations: 'സമീപകാല സംഭാഷണങ്ങൾ',
    viewAll: 'എല്ലാം കാണുക',
    noConversationsYet: 'ഇതുവരെ സംഭാഷണങ്ങളൊന്നുമില്ല',
    whenYouStartSession: 'നിങ്ങൾ ഒരു സെഷൻ ആരംഭിക്കുമ്പോൾ സംഗ്രഹങ്ങൾ ഇവിടെ കാണാം.',
    reportReady: 'റിപ്പോർട്ട് തയ്യാറാണ്',
    inProgress: 'പുരോഗമിക്കുന്നു',
    viewReport: 'റിപ്പോർട്ട് കാണുക',
    nextAppointment: 'അടുത്ത അപ്പോയിന്റ്മെന്റ്',
    noAppointmentAdded: 'അപ്പോയിന്റ്മെന്റ് ചേർത്തിട്ടില്ല',
    addDateToKeepPrep: 'തീയതി ചേർക്കുക.',
    addAppointment: '+ അപ്പോയിന്റ്മെന്റ് ചേർക്കുക',
    crisisNotice: 'അടിയന്തര പിന്തുണ വേണോ? ദയവായി ഡോക്ടർമാരുമായി ബന്ധപ്പെടുക.',
    sessionTimer: 'സംഭാഷണ സെഷൻ',
    sessionHeadline: 'സമയം എടുക്കുക. തയ്യാറാകുമ്പോൾ സംസാരിക്കുക.',
    speakPlaceholder: 'നിങ്ങളുടെ വാക്കുകൾ ഇവിടെ കാണാം...',
    typePlaceholder: 'അല്ലെങ്കിൽ നിങ്ങളുടെ ചിന്തകൾ ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    sendConversation: 'അയക്കുക',
    finishAndSummary: 'പൂർത്തിയാക്കി സംഗ്രഹം സൃഷ്ടിക്കുക',
    synthesizingSummary: 'സംഗ്രഹം തയ്യാറാക്കുന്നു...',
    reportSummaryTitle: 'സംഭാഷണ സംഗ്രഹം',
    privateIntakeDoc: 'സ്വകാര്യ രേഖ',
    reportNotice: 'പങ്കിടുന്നതിന് മുമ്പ് പരിശോധിക്കുക.',
    inYourWords: 'നിങ്ങളുടെ വാക്കുകളിൽ',
    summaryOverview: 'സംഗ്രഹ അവലോകനം',
    print: 'പ്രിന്റ് ചെയ്യുക',
    shareWithTherapist: 'പങ്കിടുക',
    linkCopied: 'ലിങ്ക് പകർത്തി!',
    returnToDashboard: 'ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക',
      logoName: "ട്രിയോറ",
    footerSlogan: "തെറാപ്പിയുടെ കൂടുതൽ മാനുഷികമായ തുടക്കത്തിനായി വോയ്‌സ്-ഫസ്റ്റ് തയ്യാറെടുപ്പ്.",
    terms: "നിബന്ധനകൾ",
    contact: "ബന്ധപ്പെടുക",
    footerDisclaimer: "© 2026 ട്രിയോറ. ട്രിയോറ പ്രതിസന്ധി സേവനം അല്ലെങ്കിൽ വൈദ്യ പരിചരണത്തിന് പകരമല്ല.",
  },
  mr: {
    howItWorks: 'हे कसे कार्य करते',
    privacy: 'गोपनीयता',
    logIn: 'लॉग इन करा',
    getStarted: 'सुरू करा',
    goToDashboard: 'डॅशबोर्डवर जा',
    heroEyebrow: 'एक शांत पहिले पाऊल',
    heroTitleLine1: 'थेरपीपूर्वी',
    heroTitleLine2: 'आपले शब्द शोधा.',
    heroSubtitle: 'तुम्हाला काय वाटत आहे हे समजून घेण्यास मदत करणारा एक खाजगी व्हॉइस संवाद.',
    startConversation: 'खाजगी संवाद सुरू करा',
    seeHowItWorks: 'हे कसे कार्य करते ते पहा',
    encryptedAndPrivate: 'एनक्रिप्टेड आणि सुरक्षित',
    noDiagnosis: 'कोणतेही वैद्यकीय निदान नाही',
    youControlSharing: 'शेअरिंग तुमच्या नियंत्रणात',
    conversationInProgress: 'संवाद सुरू आहे',
    listening: 'ऐकत आहे',
    speakNaturally: 'सहजतेने बोला.',
    heroCardQuestion: '"अलीकडे तुम्हाला सर्वात जास्त काय कठीण वाटत आहे?"',
    statementKicker: 'थेरपी सुरू करणे कठीण वाटू शकते.',
    statementHeadingLine1: 'ट्रिओरा तुम्हाला आधीच',
    statementHeadingLine2: 'समजले असल्याचे अनुभव देते.',
    howItWorksEyebrow: 'कार्यपद्धती',
    howItWorksTitleLine1: 'तीन सोप्या पायऱ्या.',
    howItWorksTitleLine2: 'एक स्पष्ट सुरुवात.',
    step1Title: 'मोकळेपणाने बोला',
    step1Desc: 'तुमच्या कम्फर्टेबल भाषेत मोकळेपणाने संवाद साधा.',
    step2Title: 'पॅटर्न समजून घ्या',
    step2Desc: 'ट्रिओरा तुमच्या विचारांची व्यवस्थित मांडणी करते.',
    step3Title: 'तुमच्या अटींवर शेअर करा',
    step3Desc: 'प्रथम तुमचा सारांश तपासा.',
    multilingualEyebrow: 'बहुभाषिक संवाद',
    multilingualTitleLine1: 'तुमची भाषा.',
    multilingualTitleLine2: 'तुमचा वेग. तुमची कहाणी.',
    multilingualDesc: 'मातृभाषेत भावना व्यक्त करणे सोपे असते.',
    privacyEyebrow: 'गोपनीयता रचना',
    privacyTitle: 'तुमची कहाणी फक्त तुमचीच राहते.',
    privacySubtitle: 'तुमचे संभाषण पूर्णपणे एनक्रिप्टेड आणि सुरक्षित आहे.',
    privacyCard1Title: 'पूर्ण एनक्रिप्शन',
    privacyCard1Desc: 'संभाषणाची उच्च सुरक्षा.',
    privacyCard2Title: 'हंगामी टोकन्स',
    privacyCard2Desc: 'संवाद संपताच ऑडिओ डेटा नष्ट होतो.',
    privacyCard3Title: 'स्पष्ट संमती',
    privacyCard3Desc: 'तुम्ही शेअर करेपर्यंत सारांश तुमच्याकडेच राहतो.',
    finalCtaTitleLine1: 'पहिले पाऊल टाका',
    finalCtaTitleLine2: 'तुमच्या स्वतःच्या शब्दांत.',
    finalCtaSub: 'सुमारे १०-१५ मिनिटे.',
    beginConversation: 'तुमचा संवाद सुरू करा',
      overview: 'आढावा',
    conversations: 'संभाषणे',
    reports: 'अहवाल',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    takeAMoment: 'थोडा वेळ घ्या. इथे कोणतीही घाई नाही.',
    privateSpaceToTalk: 'बोलण्यासाठी एक खाजगी जागा',
    whatsOnYourMind: 'तुमच्या मनात काय आहे?',
    speakFreely1015: '10-15 मिनिटे मोकळेपणाने बोला.',
    nothingSharedWithoutYou: 'तुमच्या परवानगीशिवाय काहीही शेअर केले जाणार नाही',
    recentConversations: 'अलीकडील संभाषणे',
    viewAll: 'सर्व पहा',
    noConversationsYet: 'अद्याप कोणतेही संभाषण नाही',
    whenYouStartSession: 'जेव्हा तुम्ही सत्र सुरू करता तेव्हा सारांश येथे दिसतील.',
    reportReady: 'अहवाल तयार आहे',
    inProgress: 'प्रगतीपथावर आहे',
    viewReport: 'अहवाल पहा',
    nextAppointment: 'तुमची पुढची अपॉइंटमेंट',
    noAppointmentAdded: 'कोणतीही अपॉइंटमेंट जोडली नाही',
    addDateToKeepPrep: 'तारीख जोडा.',
    addAppointment: '+ अपॉइंटमेंट जोडा',
    crisisNotice: 'तातडीची मदत हवी आहे का? कृपया डॉक्टरांशी संपर्क साधा.',
    sessionTimer: 'संभाषण सत्र',
    sessionHeadline: 'वेळ घ्या. तयार झाल्यावर बोला.',
    speakPlaceholder: 'तुमचे शब्द येथे दिसतील...',
    typePlaceholder: 'किंवा तुमचे विचार येथे टाईप करा...',
    sendConversation: 'पाठवा',
    finishAndSummary: 'पूर्ण करा आणि सारांश तयार करा',
    synthesizingSummary: 'सारांश तयार करत आहे...',
    reportSummaryTitle: 'संभाषणाचा सारांश',
    privateIntakeDoc: 'खाजगी दस्तऐवज',
    reportNotice: 'शेअर करण्यापूर्वी तपासा.',
    inYourWords: 'तुमच्या शब्दात',
    summaryOverview: 'सारांश आढावा',
    print: 'प्रिंट करा',
    shareWithTherapist: 'शेअर करा',
    linkCopied: 'लिंक कॉपी केली!',
    returnToDashboard: 'डॅशबोर्डवर परत जा',
      logoName: "त्रियोरा",
    footerSlogan: "थेरपीच्या अधिक मानवी सुरुवातीसाठी व्हॉइस-फर्स्ट तयारी.",
    terms: "अटी",
    contact: "संपर्क",
    footerDisclaimer: "© 2026 त्रियोरा. त्रियोरा ही आपत्कालीन सेवा किंवा वैद्यकीय उपचारांना पर्याय नाही.",
  },
  bn: {
    howItWorks: 'এটি যেভাবে কাজ করে',
    privacy: 'গোপনীয়তা',
    logIn: 'লগ ইন করুন',
    getStarted: 'শুরু করুন',
    goToDashboard: 'ড্যাশবোর্ডে যান',
    heroEyebrow: 'একটি শান্ত প্রথম পদক্ষেপ',
    heroTitleLine1: 'থেরাপির আগে',
    heroTitleLine2: 'নিজের ভাষা খুঁজুন।',
    heroSubtitle: 'একটি ব্যক্তিগত ভয়েস কথোপকথন যা আপনি কী অনুভব করছেন তা বুঝতে সাহায্য করে।',
    startConversation: 'একটি ব্যক্তিগত কথোপকথন শুরু করুন',
    seeHowItWorks: 'কীভাবে কাজ করে দেখুন',
    encryptedAndPrivate: 'এনক্রিপ্টেড এবং ব্যক্তিগত',
    noDiagnosis: 'কোন মেডিকেল ডায়াগনোসিস নেই',
    youControlSharing: 'শেয়ারিং আপনার নিয়ন্ত্রণে',
    conversationInProgress: 'কথোপকথন চলছে',
    listening: 'শুনছে',
    speakNaturally: 'স্বাভাবিকভাবে বলুন।',
    heroCardQuestion: '"সম্প্রতি আপনার কাছে কী সবচেয়ে কঠিন মনে হচ্ছে?"',
    statementKicker: 'থেরাপি শুরু করা কঠিন মনে হতে পারে।',
    statementHeadingLine1: 'ত্রিওরা আপনাকে আগেই',
    statementHeadingLine2: 'বোঝাপড়ার অনুভূতি দেয়।',
    howItWorksEyebrow: 'কার্যপ্রণালী',
    howItWorksTitleLine1: 'তিনটি সহজ ধাপ।',
    howItWorksTitleLine2: 'একটি স্পষ্ট সূচনা।',
    step1Title: 'খোলামেলা কথা বলুন',
    step1Desc: 'আপনার পছন্দের ভাষায় স্বতঃস্ফূর্তভাবে কথা বলুন।',
    step2Title: 'ধরণগুলো বুঝুন',
    step2Desc: 'ত্রিওরা আপনার অনুভূতিগুলোকে গুছিয়ে তোলে।',
    step3Title: 'নিজের শর্তে শেয়ার করুন',
    step3Desc: 'প্রথমে আপনার সারসংক্ষেপ দেখে নিন।',
    multilingualEyebrow: 'বহুভাষিক কথোপকথন',
    multilingualTitleLine1: 'আপনার ভাষা।',
    multilingualTitleLine2: 'আপনার গতি। আপনার গল্প।',
    multilingualDesc: 'নিজের ভাষায় অনুভূতি প্রকাশ করা সবচেয়ে সহজ।',
    privacyEyebrow: 'গোপনীয়তার প্রতিশ্রুতি',
    privacyTitle: 'আপনার গল্প শুধুই আপনার।',
    privacySubtitle: 'আপনার সমস্ত কথোপকথন সম্পূর্ণ সুরক্ষিত।',
    privacyCard1Title: 'সম্পূর্ণ এনক্রিপশন',
    privacyCard1Desc: 'আপনার তথ্য সম্পূর্ণ গোপন থাকে।',
    privacyCard2Title: 'সাময়িক টোকেন',
    privacyCard2Desc: 'কথোপকথন শেষে অডিও টোকেন মুছে যায়।',
    privacyCard3Title: 'স্পষ্ট সম্মতি',
    privacyCard3Desc: 'শেয়ার না করা পর্যন্ত সারসংক্ষেপ আপনার কাছেই থাকবে।',
    finalCtaTitleLine1: 'প্রথম পদক্ষেপ নিন',
    finalCtaTitleLine2: 'নিজের ভাষায়।',
    finalCtaSub: 'প্রায় ১০-১৫ মিনিট।',
    beginConversation: 'আপনার কথোপকথন শুরু করুন',
      overview: 'ওভারভিউ',
    conversations: 'কথোপকথন',
    reports: 'রিপোর্ট',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    takeAMoment: 'একটু সময় নিন। এখানে কোন তাড়া নেই।',
    privateSpaceToTalk: 'কথা বলার জন্য একটি ব্যক্তিগত জায়গা',
    whatsOnYourMind: 'আপনার মনে কি আছে?',
    speakFreely1015: '10-15 মিনিটের জন্য অবাধে কথা বলুন।',
    nothingSharedWithoutYou: 'আপনার অনুমতি ছাড়া কিছুই শেয়ার করা হবে না',
    recentConversations: 'সাম্প্রতিক কথোপকথন',
    viewAll: 'সব দেখুন',
    noConversationsYet: 'এখনও কোনো কথোপকথন নেই',
    whenYouStartSession: 'সেশন শুরু করলে সারাংশগুলি এখানে দেখা যাবে।',
    reportReady: 'রিপোর্ট প্রস্তুত',
    inProgress: 'চলছে',
    viewReport: 'রিপোর্ট দেখুন',
    nextAppointment: 'আপনার পরবর্তী অ্যাপয়েন্টমেন্ট',
    noAppointmentAdded: 'কোন অ্যাপয়েন্টমেন্ট যোগ করা হয়নি',
    addDateToKeepPrep: 'তারিখ যোগ করুন।',
    addAppointment: '+ অ্যাপয়েন্টমেন্ট যোগ করুন',
    crisisNotice: 'জরুরী সহায়তা প্রয়োজন? ডাক্তারদের সাথে যোগাযোগ করুন।',
    sessionTimer: 'কথোপকথন সেশন',
    sessionHeadline: 'সময় নিন। প্রস্তুত হলে কথা বলুন।',
    speakPlaceholder: 'আপনার কথা এখানে দেখা যাবে...',
    typePlaceholder: 'বা আপনার চিন্তা এখানে টাইপ করুন...',
    sendConversation: 'পাঠান',
    finishAndSummary: 'শেষ করুন এবং সারাংশ তৈরি করুন',
    synthesizingSummary: 'সারাংশ প্রস্তুত করা হচ্ছে...',
    reportSummaryTitle: 'কথোপকথনের সারাংশ',
    privateIntakeDoc: 'ব্যক্তিগত নথি',
    reportNotice: 'শেয়ার করার আগে পর্যালোচনা করুন।',
    inYourWords: 'আপনার কথায়',
    summaryOverview: 'সারাংশের ওভারভিউ',
    print: 'প্রিন্ট করুন',
    shareWithTherapist: 'শেয়ার করুন',
    linkCopied: 'লিঙ্ক কপি করা হয়েছে!',
    returnToDashboard: 'ড্যাশবোর্ডে ফিরে যান',
      logoName: "ট্রিওরা",
    footerSlogan: "থেরাপির আরও মানবিক শুরুর জন্য ভয়েস-ফার্স্ট প্রস্তুতি।",
    terms: "শর্তাবলী",
    contact: "যোগাযোগ",
    footerDisclaimer: "© 2026 ট্রিওরা। ট্রিওরা কোনো সংকটকালীন পরিষেবা বা চিকিৎসার বিকল্প নয়।",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('triora_lang') as LanguageCode;
    if (saved && TRANSLATIONS[saved]) return saved;
    return (user?.profile?.preferredLanguage as LanguageCode) || 'en';
  });

  // Sync language with user profile only if user has a language and localStorage doesn't override it
  useEffect(() => {
    const saved = localStorage.getItem('triora_lang') as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    } else if (user?.profile?.preferredLanguage && TRANSLATIONS[user.profile.preferredLanguage as LanguageCode]) {
      setLanguageState(user.profile.preferredLanguage as LanguageCode);
    }
  }, [user?.profile?.preferredLanguage]);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('triora_lang', lang);
  };

  const rawT = TRANSLATIONS[language] || TRANSLATIONS.en;
  const t = new Proxy(rawT, {
    get: (target, prop: keyof Translations) => {
      return target[prop] || TRANSLATIONS.en[prop] || prop;
    },
  });

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
